/**
 * Auto-generated by deploy.ps1 — do not edit manually.
 * Generated: 2026-06-11T23:37:41Z
 */
export const environment = {
  production: true,
  apiUrl: "https://us-central1-kephothoagenticai.run.app",
  apiTimeout: 30000,
  enableLogging: false,
  features: {
    silentPandemicScan: true,
    followUpTracking: true,
    protocolSearch: true,
    chwRegistry: true,
    referralTracking: true,
    crossCountySpread: true,
    offlineSync: true,
    liveAudio: true,
    tts: true,
  },
  surveillanceIntervalMs: 21600000,
  silentPandemicWeeks: 4,
  followUpPollIntervalMs: 300000,
  gateTimeoutMs: 60000,
};
